<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied' => 'Acceso denegado',
    'Active' => 'Activo',
    'Add' => 'Agregar',
    'Admin' => 'Admin',
    'All' => 'Todos',
    'Amount' => 'Monto',
    'Are you sure?' => '¿Está seguro?',
    'Average' => 'Promedio',
    'Avg.' => 'Prom.',
    'Begin' => 'Comenzar',
    'Body:' => 'Cuerpo:',
    'Cancel' => 'Cancelar',
    'Check your email for further instructions.' => 'Revise su buzón de correo para más instrucciones.',
    'Clients' => 'Clientes',
    'Concept' => 'Concepto',
    'Contact administrator' => 'Contactar administrador',
    'Create' => 'Crear',
    'Creator' => 'Creador',
    'Date' => 'Fecha',
    'Date and Time' => 'Fecha y hora',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'Download Presentation' => 'Descargar Presentación',
    'Edit' => 'Editar',
    'Email' => 'Correo electrónico',
    'Empowerment Foundation' => 'Fundación Empowerment',
    'Export' => 'Exportar',
    'Female' => 'Femenino',
    'Gender' => 'Género',
    'High' => 'Alto',
    'Home' => 'Inicio',
    'Log' => 'Historial',
    'Logged in as {username}.' => 'Ingresado como {username}',
    'Logout' => 'Salir',
    'Low' => 'Bajo',
    'Male' => 'Masculino',
    'Medium' => 'Medio',
    'Name' => 'Nombre',
    'New password was saved.' => 'Nueva contraseña guardada.',
    'Other' => 'Otro',
    'Password reset' => 'Reiniciar contraseña',
    'Password reset for VACH' => 'Reinicio de contraseña para VACH',
    'Payment confirmation' => 'Confirmación de pago',
    'Phone' => 'Teléfono',
    'Please fill out your email. A link to reset password will be sent there.' => 'Por favor complete con su correo eletrónico. Allí se le enviará un link para reiniciar su contraseña.',
    'Powered by' => 'Potenciado por',
    'Printable' => 'Imprimible',
    'Printable version' => 'Versión imprimible',
    'Problem: ' => 'Problema: ',
    'Redirecting...' => 'Redirigiendo...',
    'Refresh' => 'Refrescar',
    'Request' => 'Solicitar',
    'Request password reset' => 'Solicitud de reinicio de contraseña',
    'Run' => 'Ejecutar',
    'Save' => 'Guardar',
    'Show' => 'Mostrar',
    'Sign in' => 'Ingresar',
    'Sign up' => 'Crear cuenta',
    'Sorry, we are unable to reset password for email provided.' => 'Disculpe, no podemos reiniciar la contraseña del email provisto.',
    'Status' => 'Estado',
    'Thanks!' => '¡Gracias!',
    'This action cannot be reverted.' => 'Esta acción no puede ser revertida.',
    'To:' => 'Para:',
    'Type' => 'Tipo',
    'Unique ID' => 'ID único',
    'Users' => 'Usuarios',
    'View' => 'Ver',
    'done' => 'listo',
    'error' => 'error',
    'init' => 'iniciado',
    'invalid' => 'inválido',
    'of' => 'de',
    'of the team' => 'del equipo',
    'or' => 'o',
    'paid' => 'pagado',
    'partial' => 'parcial',
    'pending' => 'pendiente',
    'valid' => 'válido',
    '{name} has been successfully added to {group}.' => '{name} ha sido existosamente agregado a {group}',
    '{name} has been successfully created.' => '{name} ha sido exitasamente creado.',
    '{name} has been successfully deleted.' => '{name} ha sido exitosamente eliminado.',
    '{name} has been successfully edited.' => '{name} ha sido exitosamente editado.',
    '{name} has been successfully removed from {group}.' => '{name} ha sido exitosamente removido de {group}',
];
