<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied' => 'Acceso denegado',
    'Add' => 'Agregar',
    'Admin' => 'Admin',
    'All' => 'Todos',
    'Are you sure to continue?' => '¿Está seguro de continuar?',
    'Average' => 'Promedio',
    'Begin' => 'Comenzar',
    'Cancel' => 'Cancelar',
    'Date' => 'Fecha',
    'Date and Time' => 'Fecha y hora',
    'Description' => 'Descripción',
    'Edit' => '@@Editar@@',
    'Email' => 'Correo eletrónico',
    'Empowerment Foundation' => 'Fundación Empowerment',
    'High' => 'Alto',
    'Home' => 'Inicio',
    'Logout' => 'Salir',
    'Low' => 'Bajo',
    'Medium' => '@@Medio@@',
    'Name' => 'Nombre',
    'Phone' => 'Teléfono',
    'Powered by' => 'Potenciado por',
    'Printable' => 'Imprimible',
    'Problem while saving: ' => 'Problemas al guardar: ',
    'Refresh' => 'Refrescar',
    'Register' => 'Registrar',
    'Run' => 'Ejecutar',
    'Save' => 'Guardar',
    'Sign in' => 'Ingresar',
    'Sign up' => '@@Registrese@@',
    'Thanks!' => '¡Gracias!',
    'This action cannot be reverted.' => 'Esta acción no puede ser revertida.',
    'Tutorial' => 'Tutorial',
    'Type' => '@@Tipo@@',
    'Users' => 'Usuarios',
    'done' => '@@listo@@',
];
