<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assessment' => 'Relevamiento',
    'Assessments' => 'Relevamientos',
    'CPC: access to {wheel_type} of assessment {assessment}' => 'CPC: acceso a {wheel_type} del relavamiento {assessment}',
    'Go to dashboard...' => 'Ir al tablero...',
    'Group wheels' => 'Ruedas grupales',
    'In order to run this wheel via smartphone, please ask' => 'Para poder ejecutar esta rueda en un teléfono celular, por favor pida a',
    'Individual wheels' => 'Ruedas individuales',
    'New assessment' => 'Nuevo relevamiento',
    'Once you click \'Save\' button, team is locked, new member are not allowed and new assessment is created.' => 'Una vez que presione el botón \'Guardar\', el equipo es bloqueado, nuevos miembros no son permitidos y un relevamiento es creado.',
    'Organizational wheels' => 'Ruedas organizacionales',
    'Please ask the audience to enter this site and token in his/her phone browser' => 'Por favor pida al público que ingrese este sitio e indeitifcador en su teléfono',
    'Run on smartphone' => 'Ejecutar en teléfono celular',
    'Run on smartphones' => 'Ejectuar en teléfonos celulares',
    'Wheel already fullfilled. Email not sent.' => 'Rueda ya completada. Correo electrónico no enviado.',
    'and click over "Run" button' => 'y presione el botón "Ejecutar"',
    'and enter this token in "Wheel Token" field' => 'e ingrese este indentificador en el campo "Identificador de rueda"',
    'to enter this site in his/her phone browser' => 'que ingrese este sitio en el navegador de su celular',
    '{wheel_type} sent to {user}.' => '{wheel_type} enviada a {user}',
];
