<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assessment' => 'Relevamiento',
    'Assessments' => 'Relevamientos',
    'CPC: access to {wheel_type} of assessment {assessment}' => 'CPC: acceso a {wheel_type} del relevamiento {assessment}',
    'Email to send' => 'Correo electrónico a enviar',
    'Go to dashboard...' => 'Ir al tablero...',
    'Go to report...' => 'Ir al informe...',
    'Group wheels' => 'Ruedas grupales',
    'Individual wheels' => 'Ruedas individuales',
    'New assessment' => 'Nuevo relevamiento',
    'Organizational wheels' => 'Ruedas organizacionales',
    'Please ask the audience to enter this site and token in his/her phone browser' => 'Por favor pida al público que ingrese este sitio e indentificador en su teléfono',
    'Please send this email' => 'Por favor envíe este correo electrónico',
    'Run on smartphones' => 'Ejectuar en teléfonos celulares',
    'Wheel already fullfilled. Email not sent.' => 'Rueda ya completada. Correo electrónico no enviado.',
    '{wheel_type} sent to {user}.' => '{wheel_type} enviada a {user}',
];
