<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assessment' => 'Relevamiento',
    'Assessment deleted.' => 'Relevamiento eliminadA',
    'CPC: access to {wheel} of assessment {assessment}' => 'CPC: acceso a {wheel} del relavamiento {assessment}',
    'CPC: {wheel} answers' => 'CPC: respuesta de {wheel}',
    'Go to dashboard...' => 'Ir al tablero...',
    'Group wheel detailed status' => 'Estado detallado de rueda grupales',
    'Group wheels' => 'Ruedas grupales',
    'Group wheels sent' => 'Ruedas grupales enviadas',
    'Individual wheels' => 'Ruedas individuales',
    'Individual wheels sent' => 'Ruedas individuales enviadas',
    'Organizational wheel detailed status' => 'Estado detallado de rueda organizacionales',
    'Organizational wheels' => 'Ruedas organizacionales',
    'Organizational wheels sent' => 'Ruedas organizacionales enviadas',
    'Send group wheels' => 'Enviar ruedas grupales',
    'Send individual wheels' => 'Enviar ruedas individuales',
    'Send organizational wheels' => 'Enviar ruedas organizacionales',
    'View detailed status' => 'Ver estado detallado',
];
