<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Company data' => 'Datos de la empresa',
    'Company has been succesfully created.' => 'Empresa ha sido creada con éxito.',
    'Company has been succesfully deleted.' => 'Empresa ha sido eliminada con éxito.',
    'Edit company' => 'Editar empresa',
    'My Companies' => 'Mis empresas',
    'New company' => 'Nueva empresa',
    'Please fill out the following fields with company data:' => 'Por favor llene los siguiente campos con los datos de la empresa:',
];
