<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Avg. mon. prod.' => 'Prod. mono. promedio',
    'Cons. gap' => 'Brecha de con.',
    'Consciousness' => 'Consciencia',
    'Dashboard' => 'Tablero',
    'Group Perception Matrix' => 'Matriz de percepción grupal',
    'Group Potential Matrix' => 'Matriz de potencialidad grupal',
    'Group Relations Matrix' => 'Matriz de relaciones grupales',
    'Group conciousness and responsability Matrix' => 'Matriz de consciancia y responsabilidad grupal',
    'Group indicators' => 'Indicatores grupales',
    'How I see me' => 'Como me veo',
    'How they see me' => 'Como me ven',
    'Individual Potential Matrix' => 'Matrix de potencialidad individual',
    'Individual Wheel' => 'Rueda individual',
    'Individual projection toward the group' => 'Proyección individual hacia el grupo',
    'Individual projection toward the organization' => 'Proyección individual hacia la organización',
    'Monofactorial productivity' => 'Productividad monofactorial',
    'Organizational Perception Matrix' => 'Matriz de percepcion organizacional',
    'Organizational Potential Matrix' => 'Matriz de potencialidad organizacional',
    'Organizational Relations Matrix' => 'Matriz de relaciones organizacionales',
    'Organizational conciousness and responsability Matrix' => 'Matriz de consciencia y responsabilidad organizacional',
    'Organizational indicators' => 'Indicadores organizacionales',
    'Responsability' => 'Responsabilidad',
    'Select assesment ...' => 'Elija relevamiento ...',
    'Select company ...' => 'Elija empresa ...',
    'Select member ...' => 'Elija miembro ...',
    'Select team ...' => 'Elija equipo ...',
    'Select wheel type ...' => 'Elija tipo de rueda ...',
    'St. dev.' => 'Desv. est.',
];
