<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'As a security issue, feedback are limited to one a month an IP.' => 'Por cuestiones de seguridad, se limitan los comentarios a uno por mes por IP',
    'Comment' => 'Comentario',
    'Effectiveness' => 'Efectividad',
    'Efficience' => 'Eficiencia',
    'Feedback' => 'Valore',
    'Feedbacks' => 'Valórenos',
    'From that point of view, we encourage you to give us feedback about your experience:' => 'Desde ese punto de vista, lo alentamos a darnos sus comentario de su experiencia:',
    'How easy was VACH to be used?' => '¿Cuán sencillo es VACH en el uso?',
    'How many time you completed the tasks VACH is intended for?' => '¿Cuántas veces ha completado las tareas para las que VACH fue diseñado?',
    'How many times you\'ve been satisfied when use it?' => '¿Cuántas veces se sintió satisfecho con su usándolo?',
    'IP' => 'IP',
    'Please feel free to give us a comment:' => 'Por favor, sientase libre de darnos un comentario:',
    'Satisfaction' => 'Satisfacción',
    'We have worked hard to give our customers the best VACH we can develop, but as every human creation is perfectible.' => 'Hemos trabajo duro para darle a nuestro clientes la mejor VACH que podamos desarrollar, pero como toda creación es perfectible.',
    'You have already given us a feedback. We are waiting to hear a new feedback next month. Thank you!' => 'Usted ya ha dado un comentario. Esperamos escuchar un nuevo comentario el próximo mes. ¡Gracias!',
    'Your feedback has been saved. Thank you!' => 'Su comentario a sido guardado. ¡Muchas gracias!',
    'easy' => 'fácil',
    'hard' => 'difícil',
    'regular' => 'regular',
    'very easy' => 'muy fácil',
    'very hard' => 'muy difícil',
];
