<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action plan' => 'Plan de acción',
    'Celebration' => 'Celebración',
    'Edit resources' => 'Editar recurso',
    'Editing goal milestone' => 'Editando hito de meta',
    'Evidence' => 'Evidencia',
    'Goal - ' => 'Meta - ',
    'Goal deleted.' => 'Meta eliminada.',
    'Goal has been succesfully created.' => 'Meta ha sido creada con éxito.',
    'Goal not delete:' => 'Meta no elimanada:',
    'Goal not saved: ' => 'Meta no guardada:',
    'Goal resources' => 'Recursos de meta',
    'Goal resources assigment' => 'Asignación de recursos de meta',
    'Goals' => 'Metas',
    'Milestone has been succesfully created.' => 'Hito ha sido creado con éxito.',
    'Milestones' => 'Hitos',
    'New goal' => 'Nueva meta',
    'New goal milestone' => 'Nuevo hito de meta',
    'New milestone' => 'Nuevo hito',
    'Please, describe all the things <b>required</b> to achieve your goal, one line each:' => 'Por favor, describa todas las cosas <b>requeridas</b> para alcanzar su meta, una por línea:',
    'Please, describe all the things that <b>prevent</b> your goal to be achieved, one line each:' => 'Por favor, describa todas las cosas que <b>evitan</b> que su meta sea cumplida, una por línea:',
    'Please, select those resources you currently have:' => 'Por favor, elija aquellos recursos que posee actualmente',
    'Resources' => 'Recursos',
    'Save and continue...' => 'Guardar y continuar...',
    'Select milestone date ...' => 'Elija una fecha de hito',
    'Things to avoid:' => 'Cosas a evitar:',
    'Things to conquer:' => 'Cosas a conquistar:',
    'Things to conservate:' => 'Cosas a conservar:',
    'Things to eliminate:' => 'Cosas a eliminar:',
    'View action plan' => 'Ver plan de acción',
];
