<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Available payments' => 'Pagos disponibles',
    'Commision' => 'Comisión',
    'Commision currency' => 'Moneda de comisión',
    'Create liquidation' => 'Crear liquidación',
    'Currency' => 'Moneda',
    'Is manual' => 'Es manual',
    'Liquidation' => 'Liquidación',
    'Liquidations' => 'Liquidaciones',
    'Local amount' => 'Monto local',
    'Mark as payed' => 'Marcar como pagados',
    'Money to add' => 'Dinero a agregar',
    'My Payments' => 'Mis pagos',
    'Net amount' => 'Monto neto',
    'Pay pendings' => 'Pagar pendientes',
    'Payment' => 'Pago',
    'Payment successfull!' => '¡Pago exitoso!!!',
    'Payments' => 'Pagos',
    'Please, wait in this page.' => 'Por favor, aguarde en esta página',
    'Rate' => 'Tasa',
    'Raw amount' => 'Monto bruto',
    'Set commision' => 'Fijar comisión',
    'There was an error' => 'Hubo un error',
    'VACH' => 'VACH',
    'VACH administrators has been notified.' => 'Los administradores de VACH han sido notificados',
    'We are going to contact you soon.' => 'Nos pondremos en contacto con usted pronto.',
    'We are going to notify you when it is fulfilled.' => 'Le notificaremos cuando esté completo.',
    'We are waiting payment broker confirmation.' => 'Estamos esperando la confirmación del intermediario.',
    'Your payment has been declined. Please try again.' => 'Su pago ha sido desestimado. Por favor intente nuevamente.',
    'Your payment is pending.' => 'Su está pendiente.',
    '{name} amount' => 'Monto {name}',
];
