<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Basic assisstance' => 'Asistencia básica',
    'No assisstance' => 'Sin asistencia',
    'Please, fill your sign up form out:' => 'Por favor, complete este formulario:',
    'Premium assisstance' => 'Asistencia preferencial',
    'Sign up' => 'Crear cuenta',
    'Sign up successfull. Welcome to VACH!' => 'Registro exitoso. ¡Bievenido a VACH!',
    'Technical assistance via any required communication device, all days, whole year.' => 'Asistencia técnica a través de cualquier dispositivo de comunicación requerido, todos los días, todo el año.',
    'Technical assistance via email, chat, teleconference, remote desktop, in labor days, in tipical commercial schedule, 9am to 6pm (Arg)' => 'Asistencia técnia a través de correo electrónico, chat, teleconferencia, escritorio remoto, en días laborales, dentro del hoarario típico de comercio, 9h a 18h (Arg)',
    'Username already used.' => 'Nombre de usuario ya usado.',
    'VACH can be used with no technical assistance.' => 'VACH puede ser usado sin asistencia técnica',
    'ar$ 200 / month' => 'ar$ 200 / mes',
    'ar$ 2000 / month' => 'ar$ 2000 / mes',
];
