<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action plan' => 'Plan de acción',
    'Analysis saved.' => 'Análisis guardado.',
    'Assessment summary' => 'Sintesis de relevamiento',
    'Competence Matrix' => 'Matriz de competencias',
    'Competences Matrix' => 'Matriz de competencias',
    'Competences Matrix of {member}' => 'Matriz de competencias de {member}',
    'Efectiveness Matrix' => 'Matriz de efectividad',
    'Emergent Matrix' => 'Matriz de emergentes',
    'Emergents Matrix' => 'Matriz de emergentes',
    'Emergents Matrix of {member}' => 'Matriz de emergentes de {member}',
    'Group and organizational performance' => 'Performance organizacional y grupal',
    'Index' => 'Índice',
    'Individual perferformance' => 'Performance individual',
    'Introduction' => 'Introducción',
    'Method fundaments' => 'Fundamentos del método',
    'Perception Matrix' => 'Matriz de percepción',
    'Perception Matrix of {member}' => 'Matriz de percepción de {member}',
    'Performance Matrix' => 'Matriz de performance',
    'Performance Matrix of {member}' => 'Matriz de performance de {member}',
    'Relations Matrix' => 'Matriz de relaciones',
    'Relations Matrix of {member}' => 'Matriz de relaciones de {member}',
    'Technical Report' => 'Reporte técnico',
];
