<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add licences' => 'Agregar licencias',
    'Begin payment' => 'Comenzar pago',
    'Buy Licences' => 'Comprar licencias',
    'Go to My Licences' => 'Ir a Mis licencias',
    'Licences' => 'Licencias',
    'Licences required' => 'Licencias requeridas',
    'My Licences' => 'Mis licencias',
    'Price' => 'Precio',
    'Price in USD $' => 'Precio es USD $',
    'Product' => 'Producto',
    'Quantity' => 'Cantidad',
    'Remove licences' => 'Quitar licencias',
    'Total' => 'Total',
    'You need {count} more licences' => 'Necesita {count} licencias más',
    'Your balance' => 'Su saldo',
];
