<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assessment has been succesfully created.' => 'Evaluación ha sido creado exitosamente.',
    'Assessment has been succesfully deleted.' => 'Evaluación ha sido eliminada exitasamente.',
    'Assessments' => 'Evaluaciones',
    'Coach' => 'Coach',
    'Company' => 'Empresa',
    'Member' => 'Miembro',
    'Members' => 'Miembros',
    'My Teams' => 'Mi equipos',
    'New assessment' => 'Nueva evaluación',
    'New member' => 'Nuevo miembro',
    'New team' => 'Nuevo equipo',
    'Please fill out the following fields with team data:' => 'Por favor, complete los campos con los datos del equipo',
    'Select new member ...' => 'Elegir nuevo miembro ...',
    'Sponsor' => 'Patrocinador',
    'Team' => 'Equipo',
    'Team data' => 'Datos del equipo',
    'Team deleted.' => 'Equipo eliminado.',
    'Team has been succesfully created.' => 'Equipo creado exitosamente.',
    'Team member has been succesfully created.' => 'Miembro de equipo creado exitosamente.',
    'Team member has been succesfully deleted.' => 'Miembro de equipo eliminado exitosamente.',
    'Team member has been succesfully saved.' => 'Miembro de equipo guardado exitosamente.',
    'Teams' => 'Equipos',
];
