<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access granted' => 'Acceso concedido',
    'Access removed' => 'Acceso quitado',
    'Allowed coaches' => 'Coaches invitados',
    'Are you sure that you want to delete this team?' => '¿Estás seguro que quiere eliminar este equipo?',
    'Assessment' => 'Relevamiento',
    'Assessment has been successfully deleted.' => 'Relevamiento ha sido eliminado con éxito',
    'Assessments' => 'Relevamientos',
    'CPC: access to {wheel_type} of team {team}' => 'CPC: acceso a {wheel_type} del relevamiento {team}',
    'Coach' => 'Coach',
    'Company' => 'Empresa',
    'Deleting team' => 'Eliminando equipo',
    'Email to send' => 'Correo electrónico a enviar',
    'Go to dashboard...' => 'Ir al tablero...',
    'Go to report...' => 'Ir al informe...',
    'Grant access' => 'Permitir acceso',
    'Group wheels' => 'Ruedas grupales',
    'Individual wheels' => 'Ruedas individuales',
    'Member' => 'Miembro',
    'Members' => 'Miembros',
    'Natural Team' => 'Equipo natural',
    'New member' => 'Nuevo miembro',
    'New team' => 'Nuevo equipo',
    'Organizational wheels' => 'Ruedas organizacionales',
    'Please ask the audience to enter this site and token in his/her phone browser' => 'Por favor pida al público que ingrese este sitio e indentificador en su teléfono',
    'Please fill out the following fields with team data:' => 'Por favor, complete los campos con los datos del equipo',
    'Please send this email' => 'Por favor envíe este correo electrónico',
    'Remove access' => 'Quitar acceso',
    'Run on smartphones' => 'Ejectuar en teléfonos celulares',
    'Select coach...' => 'Elija coach...',
    'Select new member...' => 'Elegir nuevo miembro...',
    'Sponsor' => 'Patrocinador',
    'Team' => 'Equipo',
    'Team data' => 'Datos del equipo',
    'Team fullfilled' => 'Equipo completado',
    'Team has been successfully deleted.' => 'Equipo ha sido exitosamente eliminado.',
    'Teams' => 'Equipos',
    'Update Team' => 'Actualizar equipo',
    'Wheel already fullfilled. Email not sent.' => 'Rueda ya completada. Correo electrónico no enviado.',
    'Wheel forms has been successfully created.' => 'Formularios de ruedas han sudi creados exitosamente.',
    '{wheel_type} sent to {user}.' => '{wheel_type} enviada a {user}',
];
