<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure that you want to delete this assessment?' => '¿Estás seguro que quiere eliminar este relevamiento?',
    'Assessments' => 'Relevamientos',
    'Coach' => 'Coach',
    'Company' => 'Empresa',
    'Deleting assessment' => 'Eliminando relevamiento',
    'Member' => 'Miembro',
    'Members' => 'Miembros',
    'Natural Team' => 'Equipo natural',
    'New assessment' => 'Nuevo relevamiento',
    'New assessment (requires team fullfilled)' => 'Nuevo relevamiento (requiere equipo completado)',
    'New member' => 'Nuevo miembro',
    'New team' => 'Nuevo equipo',
    'Please fill out the following fields with team data:' => 'Por favor, complete los campos con los datos del equipo',
    'Select coach ...' => 'Elija coach...',
    'Select new member ...' => 'Elegir nuevo miembro ...',
    'Sponsor' => 'Patrocinador',
    'Team' => 'Equipo',
    'Team data' => 'Datos del equipo',
    'Team fullfilled' => 'Equipo completado',
    'Teams' => 'Equipos',
];
