<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answers' => 'Respuestas',
    'Coach' => 'Coach',
    'Email already used.' => 'Correo electrónico ya usado.',
    'I\'m coach' => 'Soy coach',
    'Is administrator' => 'Es administrador',
    'My Data' => 'Mis datos',
    'New password' => 'Nueva contraseña',
    'New person' => 'Nueva persona',
    'New user' => 'Nuevo usuario',
    'Old password' => 'Antigua contraseña',
    'Password' => 'Contraseña',
    'Password confirmation' => 'Confirmar contraseña',
    'Passwords don\'t match.' => 'Contraseñas no coinciden',
    'Person' => 'Persona',
    'Persons' => 'Personas',
    'Please fill out the following fields with person data:' => 'Por favor, rellene el formulario con los datos de la persona:',
    'Please fill out the following fields with user personal data:' => 'Por favor, complete los campos con los datos personales del usuario:',
    'Please fill out the following fields with your personal data:' => 'Por favor, complete los campos con sus datos personales:',
    'Re-enter password' => 'Re-ingrese contraseña',
    'Remember me' => 'Recuerdeme',
    'Shortname or initials' => 'Nombre corto o iniciales',
    'Surname' => 'Apellido',
    'Username' => 'Nombre usuario',
    'Users' => 'Usuarios',
    'Wrong old password.' => 'Antigua contraseña incorrecta',
    'Your personal data has been successfully saved.' => 'Sus datos personales han sido salvado con éxito.',
];
