<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answers' => 'Respuestas',
    'Client' => 'Cliente',
    'Client has been succesfully created.' => 'Cliente ha sido creado con éxito.',
    'Client has been succesfully deleted.' => 'Cliente ha sido eliminado con éxito.',
    'Client not deleted: ' => 'Cliente no eliminado: ',
    'Client not saved: ' => 'Cliente no guardado: ',
    'Clients' => 'Clientes',
    'Coach' => 'Coach',
    'Editing client' => 'Editando cliente',
    'Email' => 'Correo electrónico',
    'Email already used.' => 'Correo electrónico ya usado.',
    'I\'m coach' => 'Soy coach',
    'If you forgot your password you can ' => 'Si olvidó su contraseña puede ',
    'My account' => 'Mi cuenta',
    'Name' => 'Nombre',
    'New client' => 'Nuevo cliente',
    'New password' => 'Nueva contraseña',
    'Old password' => 'Antigua contraseña',
    'Password' => 'Contraseña',
    'Password don\'t match.' => 'Contraseñas no coinciden.',
    'Passwords don\'t match.' => '',
    'Please fill out the following fields with client data:' => 'Por favor, rellene el formulario con los datos del cliente:',
    'Re-enter password' => 'Re-ingrese contraseña',
    'Remember me' => 'Recuerdeme',
    'Surname' => 'Apellido',
    'Username' => 'Nombre usuario',
    'Wheels' => 'Ruedas',
    'Wrong old password.' => 'Antigua contraseña incorrecta',
    'reset it' => 'resetearlo',
    'username' => 'Nombre de usuario',
];
