<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answer type' => 'Tipo de respuesta',
    'Compare to' => 'Comparar con',
    'Date' => 'Fecha',
    'Dimension' => 'Dimensión',
    'New wheel' => 'Nueva rueda',
    'Order' => 'Orden',
    'Question' => 'Pregunta',
    'Running wheel' => 'Ejecutando rueda',
    'Save and finish' => 'Guardar y finalizar',
    'Save and next dimension...' => 'Guardar y próxima dimensión',
    'Some answers left.' => 'Faltan alguna respuestas',
    'Some answers missed' => 'Alguna respuestas faltan',
    'Value' => 'Valor',
    'View answers' => 'Ver respuestas',
    'Wheel' => 'Rueda',
    'Wheel deleted.' => 'Rueda eliminada.',
    'Wheel not delete:' => 'Rueda no eliminada:',
    'Wheels' => 'Ruedas',
    'absolutly' => 'absolutamente',
    'all' => 'todo',
    'always' => 'siempre',
    'answers' => 'respuestas',
    'bad' => 'mal',
    'continue...' => 'continuar...',
    'fair' => 'suficiente',
    'few' => 'poco',
    'good' => 'bien',
    'many' => 'mucho',
    'mostly' => 'mayormente',
    'never' => 'nunca',
    'none' => 'ninguno',
    'often' => 'a menudo',
    'optimal' => 'óptimo',
    'rarely' => 'raramente',
    'regularly' => 'regularmente',
    'some' => 'algo',
    'sometimes' => 'a veces',
    'usually' => 'seguido',
    'worst' => 'pésimo',
];
