<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answer type' => 'Tipo de respuesta',
    'Appropriateness' => 'Pertinencia',
    'Belonging' => 'Pertenencia',
    'Change Management' => 'Gestión del cambio',
    'Client guidance' => 'Orientación al cliente',
    'Communication' => 'Comunicación',
    'Compare to' => 'Comparar con',
    'Conflict resolution' => 'Resolución de conflictos',
    'Creativity' => 'Creatividad',
    'Date' => 'Fecha',
    'Dimension' => 'Dimensión',
    'Editing wheel questions' => 'Editando las preguntas de las ruedas',
    'Emotional Dimension' => 'Dimensión emocional',
    'Existential Dimension' => 'Dimensión existencial',
    'Family' => 'Familia',
    'Flexibility' => 'Flexibilidad',
    'Free time' => 'Tiempo libre',
    'Group Wheel' => 'Rueda grupal',
    'Identity' => 'Identidad',
    'Individual Wheel' => 'Rueda individual',
    'Individual projection toward the group' => 'Proyección Individual hacia el grupo',
    'Individual projection toward the organization' => 'Proyección Individual hacia la organización',
    'Initiative' => 'Iniciativa',
    'Leadership' => 'Liderazgo',
    'Legitimation' => 'Legitimación',
    'Mental Dimension' => 'Dimensión mental',
    'New wheel' => 'Nueva rueda',
    'Observed' => 'Observado',
    'Observer' => 'Observador',
    'Observer  Observed' => 'Observador \\ Observado',
    'Order' => 'Orden',
    'Organizational Wheel ' => 'Rueda organizacional',
    'Physical Dimension' => 'Dimensión física',
    'Quality guidance' => 'Orientación a la calidad',
    'Question' => 'Pregunta',
    'Results guidance' => 'Orientación a los resultados',
    'Running group wheel' => 'Ejecutando rueda grupal',
    'Running individual wheel' => 'Ejecutando rueda individual',
    'Running organizational wheel' => 'Ejecutando rueda organizacional',
    'Save and finish' => 'Guardar y finalizar',
    'Save and next dimension...' => 'Guardar y próxima dimensión',
    'Some answers left.' => 'Faltan alguna respuestas',
    'Some answers missed' => 'Alguna respuestas faltan',
    'Spiritual Dimension' => 'Dimensión espiritual',
    'Strategic vision' => 'Visión estratégica',
    'Team work' => 'Trabajo en equipo',
    'Thanks!' => 'Gracias!',
    'Value' => 'Valor',
    'View answers' => 'Ver respuestas',
    'Wheel' => 'Rueda',
    'Wheel Questions' => 'Preguntas de ruedas',
    'Wheel deleted.' => 'Rueda eliminada.',
    'Wheel not delete:' => 'Rueda no eliminada:',
    'Wheel questions saved.' => 'La preguntas de ruedas guardadas.',
    'Wheels' => 'Ruedas',
    'Work' => 'Trabajo',
    'You\'ve successfully answered all questions!' => 'Ha contestado existosamente todas las preguntas!',
    'absolutly' => 'absolutamente',
    'all' => 'todo',
    'always' => 'siempre',
    'answers' => 'respuestas',
    'bad' => 'mal',
    'continue...' => 'continuar...',
    'fair' => 'suficiente',
    'few' => 'poco',
    'good' => 'bien',
    'many' => 'mucho',
    'mostly' => 'mayormente',
    'never' => 'nunca',
    'none' => 'ninguno',
    'often' => 'a menudo',
    'optimal' => 'óptimo',
    'rarely' => 'raramente',
    'regularly' => 'regularmente',
    'some' => 'algo',
    'sometimes' => 'a veces',
    'usually' => 'seguido',
    'worst' => 'pésimo',
];
