FROM ubuntu:bionic

MAINTAINER Marcelo Briones <ing@marcelobriones.com.ar>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y install \
    curl wget inetutils-ping nano mysql-client git zip \
    apache2 libapache2-mod-php \
    php php-curl php-mysql php-zip php-xml php-mbstring php-intl php-gd php-xdebug

RUN rm -rf /var/lib/apt/lists/*

#COPY auth.json /root/.composer/auth.json
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#RUN /usr/local/bin/composer global require "fxp/composer-asset-plugin:*"

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

RUN /usr/sbin/a2enmod rewrite

RUN sed -i "s/upload_max_filesize = 2M/upload_max_filesize = 20M/g" /etc/php/7.2/apache2/php.ini

ENV PATH="/var/www/html/vendor/bin:${PATH}"

WORKDIR /var/www/html

EXPOSE 80

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]